# Generated by Django 4.1.3 on 2023-01-11 12:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(100)])),
                ('subtitle', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(100)])),
                ('img_url', models.URLField()),
                ('body', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
