# Generated by Django 4.1.3 on 2023-01-18 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('subtitle', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('futured_image', models.ImageField(blank=True, default='eyes-block-2.png', null=True, upload_to='')),
                ('body', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
