# Generated by Django 4.1.3 on 2023-01-11 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_subtitle_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
