# Generated by Django 4.1.3 on 2023-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_url',
        ),
        migrations.AddField(
            model_name='post',
            name='futured_image',
            field=models.ImageField(blank=True, default='eyes-block-2.png', null=True, upload_to=''),
        ),
    ]
